### ISSUE TITLE
How to run locally

### ISSUE THREAD

**Issue by skychan** [stoneMo/DeepAVFusion#3]
How to test locally?
The given script is only for the slrum cluster, don't know how to run locally.

Also, the fie `Downloading: "assets/models/vitbase_audiomae_as2m.pth"` is missing, not able to run.

**Comment by Cb1ock** [comment]
same here, need the pretrained checkpoint

**Comment by pedro-morgado** [comment]
checkpoint added.
regarding running locally, you just run with `env.slurm=False`.

**Comment by pedro-morgado** [comment]
done
